{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3b884596-9f77-4eea-8f25-baa0d607cd4f",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'some_condition' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 15\u001b[0m\n\u001b[1;32m     11\u001b[0m     \u001b[38;5;28;01mpass\u001b[39;00m\n\u001b[1;32m     13\u001b[0m \u001b[38;5;124;03m'''Here, we inherit from the built-in Exception class to create our custom exception. Now, \u001b[39;00m\n\u001b[1;32m     14\u001b[0m \u001b[38;5;124;03mwe can raise our CustomError exception whenever the condition we defined is met in our code:'''\u001b[39;00m\n\u001b[0;32m---> 15\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[43msome_condition\u001b[49m:\n\u001b[1;32m     16\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m CustomError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mAn error occurred!\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mNameError\u001b[0m: name 'some_condition' is not defined"
     ]
    }
   ],
   "source": [
    "'''Q1- Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Note: Here Exception class refers to the base class for all the exceptions.\n",
    "\n",
    "In Python, Exception is the base class for all the built-in and user-defined exceptions. It provides a set of common methods and attributes that all exceptions can use. When creating a custom exception, we need to inherit from the Exception class to take advantage of these methods and attributes.\n",
    "\n",
    "By inheriting from the Exception class, our custom exception automatically gets access to the common methods and attributes provided by the Exception class, such as the ability to print out a detailed traceback when an exception occurs. Additionally, by using the Exception class as the base class for our custom exception, we ensure that our custom exception is compatible with the existing exception handling mechanisms in Python.\n",
    "\n",
    "For example, let's say we want to create a custom exception called CustomError that is raised when a certain condition is met in our code. We can define the CustomError class as follows:'''\n",
    "\n",
    "class CustomError(Exception):\n",
    "    pass\n",
    "\n",
    "'''Here, we inherit from the built-in Exception class to create our custom exception. Now, \n",
    "we can raise our CustomError exception whenever the condition we defined is met in our code:'''\n",
    "if some_condition:\n",
    "    raise CustomError(\"An error occurred!\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9cfc6e09-3336-4022-8cd6-af94f41beff1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Help on class Exception in module builtins:\n",
      "\n",
      "class Exception(BaseException)\n",
      " |  Common base class for all non-exit exceptions.\n",
      " |  \n",
      " |  Method resolution order:\n",
      " |      Exception\n",
      " |      BaseException\n",
      " |      object\n",
      " |  \n",
      " |  Built-in subclasses:\n",
      " |      ArithmeticError\n",
      " |      AssertionError\n",
      " |      AttributeError\n",
      " |      BufferError\n",
      " |      ... and 15 other subclasses\n",
      " |  \n",
      " |  Methods defined here:\n",
      " |  \n",
      " |  __init__(self, /, *args, **kwargs)\n",
      " |      Initialize self.  See help(type(self)) for accurate signature.\n",
      " |  \n",
      " |  ----------------------------------------------------------------------\n",
      " |  Static methods defined here:\n",
      " |  \n",
      " |  __new__(*args, **kwargs) from builtins.type\n",
      " |      Create and return a new object.  See help(type) for accurate signature.\n",
      " |  \n",
      " |  ----------------------------------------------------------------------\n",
      " |  Methods inherited from BaseException:\n",
      " |  \n",
      " |  __delattr__(self, name, /)\n",
      " |      Implement delattr(self, name).\n",
      " |  \n",
      " |  __getattribute__(self, name, /)\n",
      " |      Return getattr(self, name).\n",
      " |  \n",
      " |  __reduce__(...)\n",
      " |      Helper for pickle.\n",
      " |  \n",
      " |  __repr__(self, /)\n",
      " |      Return repr(self).\n",
      " |  \n",
      " |  __setattr__(self, name, value, /)\n",
      " |      Implement setattr(self, name, value).\n",
      " |  \n",
      " |  __setstate__(...)\n",
      " |  \n",
      " |  __str__(self, /)\n",
      " |      Return str(self).\n",
      " |  \n",
      " |  with_traceback(...)\n",
      " |      Exception.with_traceback(tb) --\n",
      " |      set self.__traceback__ to tb and return self.\n",
      " |  \n",
      " |  ----------------------------------------------------------------------\n",
      " |  Data descriptors inherited from BaseException:\n",
      " |  \n",
      " |  __cause__\n",
      " |      exception cause\n",
      " |  \n",
      " |  __context__\n",
      " |      exception context\n",
      " |  \n",
      " |  __dict__\n",
      " |  \n",
      " |  __suppress_context__\n",
      " |  \n",
      " |  __traceback__\n",
      " |  \n",
      " |  args\n",
      "\n",
      "['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', 'args', 'with_traceback']\n"
     ]
    }
   ],
   "source": [
    "'''Q2- Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "You can print the Python Exception Hierarchy using the help() function in Python. Here's an example code:'''\n",
    "\n",
    "help(Exception)\n",
    "\n",
    "'''When you run this code, you will get a detailed description of the Exception class and its subclass hierarchy in the Python interpreter console.\n",
    "\n",
    "Alternatively, you can also use the dir() function to list all the attributes and methods of the Exception class and its subclasses. Here's an example code:'''\n",
    "\n",
    "print(dir(Exception))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "70d8e130-bb6e-4ff1-a5a3-82b7b6b9f65d",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 9\u001b[0m\n\u001b[1;32m      7\u001b[0m a \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m10\u001b[39m\n\u001b[1;32m      8\u001b[0m b \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[0;32m----> 9\u001b[0m c \u001b[38;5;241m=\u001b[39m \u001b[43ma\u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[43mb\u001b[49m  \u001b[38;5;66;03m# ZeroDivisionError: division by zero\u001b[39;00m\n\u001b[1;32m     11\u001b[0m \u001b[38;5;124;03m'''2-OverflowError: This error occurs when a calculation exceeds the maximum limit of a numeric type. For example:'''\u001b[39;00m\n\u001b[1;32m     12\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01msys\u001b[39;00m\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "'''Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "The ArithmeticError class is a built-in Python class that defines errors that occur during numeric calculations. Some of the errors defined in the ArithmeticError class are:\n",
    "\n",
    "1- ZeroDivisionError: This error occurs when a number is divided by zero. For example:'''\n",
    "\n",
    "a = 10\n",
    "b = 0\n",
    "c = a/b  # ZeroDivisionError: division by zero\n",
    "\n",
    "'''2-OverflowError: This error occurs when a calculation exceeds the maximum limit of a numeric type. For example:'''\n",
    "import sys\n",
    "\n",
    "a = sys.maxsize  # Maximum value for integers on this system\n",
    "b = a*a         # OverflowError: integer multiplication result too large\n",
    "\n",
    "'''In both these examples, the program encounters an error while performing a calculation. \n",
    "The error is caught by the interpreter and raised as an ArithmeticError because it falls under the category of errors that occur \n",
    "during numeric calculations.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64dc211c-e249-42d4-99d5-99cef72f42b9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "'''The LookupError class is a base class for all the exceptions that occur when a specified key or index cannot be found. It is a subclass of the Exception class and a superclass of several other exception classes.\n",
    "\n",
    "The KeyError and IndexError are two common exceptions that inherit from the LookupError class.\n",
    "\n",
    "KeyError is raised when a key is not found in a dictionary. For example:'''\n",
    "# defining a dictionary\n",
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "\n",
    "# accessing a non-existing key\n",
    "try:\n",
    "    value = my_dict['d']\n",
    "except KeyError:\n",
    "    print(\"Key not found in the dictionary\")\n",
    "\n",
    "# Output: Key not found in the dictionary\n",
    "'''IndexError is raised when an index is out of range of a sequence (such as a list, tuple or string). For example:'''\n",
    "\n",
    "# defining a list\n",
    "my_list = [1, 2, 3]\n",
    "\n",
    "# accessing an element at an index that is out of range\n",
    "try:\n",
    "    value = my_list[3]\n",
    "except IndexError:\n",
    "    print(\"Index out of range\")\n",
    "\n",
    "# Output: Index out of range\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "514878e8-d4d3-4218-bcc2-e2eb03d2abc5",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "'''In Python, ImportError is an exception that is raised when the import statement cannot find the module to import or when there is an error in importing the module. This can occur when the module is not installed, when the module is not present in the current working directory or in the list of directories in the PYTHONPATH environment variable.\n",
    "\n",
    "For example, suppose we have a Python program that uses the pandas library, but the library is not installed on the system. When we try to run the program, we will get an ImportError:'''\n",
    "\n",
    "import pandas\n",
    "\n",
    "ModuleNotFoundError: No module named 'pandas'\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a6384d05-0fa5-4ceb-88a6-7b3c79a981d4",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q6. List down some best practices for exception handling in python.\n",
    "Here are some best practices for exception handling in Python:\n",
    "\n",
    "    1.-Use specific exception types: Catching and handling specific exception types rather than using a generic exception handler for all types of exceptions.\n",
    "\n",
    "    2.-Keep exception handling code separate: Keep the code that handles exceptions separate from the main code for better readability and maintainability.\n",
    "\n",
    "    3.-Handle exceptions as close to the source as possible: Handle exceptions as close to the source as possible to avoid unnecessary code execution.\n",
    "\n",
    "    4.-Avoid using bare except clauses: Bare except clauses catch all types of exceptions, which makes debugging difficult. Instead, use specific exception types or at least catch the base Exception class.\n",
    "\n",
    "    5.-Use try-finally or with statements to ensure clean-up actions: Use try-finally or with statements to ensure that clean-up actions are always performed, regardless of whether an exception is raised or not.\n",
    "\n",
    "    6.-Provide informative error messages: Provide informative error messages that explain what went wrong and how the user can fix it.\n",
    "\n",
    "    7.-Log errors: Use a logging framework to log errors and exceptions for easier debugging and troubleshooting.\n",
    "\n",
    "    8.-Raise exceptions when needed: Raise exceptions when necessary, such as when a precondition is not met, to signal an error to the caller.\n",
    "\n",
    "    9.-Keep exception handling simple: Avoid overcomplicating exception handling logic, as this can make the code harder to understand and maintain.\n",
    "\n",
    "    10.-Test exception handling code: Test the exception handling code to ensure that it works as intended and handles all possible scenarios.'''\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
